### ISSUE TITLE
Bluepost issues

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#108]
- Blueposts are not blue. Instead they use the default white font color. If this is a theme related issue pls name the css code for this.

- Replies with a staff account are not seen as blueposts. Usually a staff-reply should also be a bluepost including font color and avatar frame

Image:
![reply](https://user-images.githubusercontent.com/18347559/34541195-a19868a6-f0d7-11e7-899f-f3c0ba207b5e.jpeg)

**Comment by fixcore** [comment]
Fixed in dev branch, please verify and confirm

**Comment by Ovahlord** [comment]
Cannot confirm. Blueposts are now completely broken:
![bluepost](https://user-images.githubusercontent.com/18347559/34653822-0f97b38a-f3f2-11e7-9dc6-b8cbcb7337d1.png)
