### ISSUE TITLE
[dev] Editing topics does not display written title or text

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#115]
Right now when you create a topic and wanna edit it afterwards the editor shows you an empty title and text page. It should display you the written text so you can edit it.

![editotpic](https://user-images.githubusercontent.com/18347559/35190607-daf98d8c-fe65-11e7-9ddb-31d7168c1c8d.png)

**Comment by fixcore** [comment]
Fixed, please confirm it.

**Comment by Ovahlord** [comment]
fixed.
