### ISSUE TITLE
Bugtracker Error Message

### ISSUE THREAD

**Issue by NoctisTheReal** [fixcore/BlizzCMS#134]
I tested the Bugtracker App and with a random bug report i get those 2 error messages
-----------------------------------------------------------------------------------------------------------
A PHP Error was encountered

Severity: Notice

Message: Undefined property: CI::$auth

Filename: core/Model.php

Line Number: 77

Backtrace:

File: D:\htdocs\acctr\application\modules\bugtracker\models\Bugtracker_model.php
Line: 96
Function: __get

File: D:\htdocs\acctr\application\modules\bugtracker\views\index.php
Line: 7
Function: insertIssue

File: D:\htdocs\acctr\application\third_party\MX\Loader.php
Line: 357
Function: include

File: D:\htdocs\acctr\application\third_party\MX\Loader.php
Line: 300
Function: _ci_load

File: D:\htdocs\acctr\application\modules\bugtracker\controllers\bugtracker.php
Line: 23
Function: view

File: D:\htdocs\acctr\index.php
Line: 315
Function: require_once

--------------------------------------------------------------------------------------------------------
An uncaught Exception was encountered

Type: Error

Message: Call to a member function insert() on null

Filename: D:\htdocs\acctr\application\modules\bugtracker\models\Bugtracker_model.php

Line Number: 96

Backtrace:

File: D:\htdocs\acctr\application\modules\bugtracker\views\index.php
Line: 7
Function: insertIssue

File: D:\htdocs\acctr\application\third_party\MX\Loader.php
Line: 357
Function: include

File: D:\htdocs\acctr\application\third_party\MX\Loader.php
Line: 300
Function: _ci_load

File: D:\htdocs\acctr\application\modules\bugtracker\controllers\bugtracker.php
Line: 23
Function: view

File: D:\htdocs\acctr\index.php
Line: 315
Function: require_once

**Comment by Ovahlord** [comment]
Cannot confirm the php errors but after submitting a bug it is not getting listed.

**Comment by DZywolf** [comment]
I can't confirm any of the two errors I need more details such as PHP version used, etc

**Comment by fixcore** [comment]
The person does not continue with the report. Closed issue
