### ISSUE TITLE
Issue in settings options and bugtracker 

### ISSUE THREAD

**Issue by DZywolf** [fixcore/BlizzCMS#155]
**Description:**

Recent changes in the structure are affecting the password/email change and Bugtracker.

**Current behaviour:**

currently with the commit 0164080ff2e07cf741cda1868f7a943e8471a4ee the syntax fails to connect with the db properly

**Branch(es):**

devs

**Browser:** Chrome, Firefox and others

**Comment by fixcore** [comment]
Fixed
