### ISSUE TITLE
[dev] Captcha system is broken

### ISSUE THREAD

**Issue by RenegadeLegionWow** [fixcore/BlizzCMS#165]
**Description:**

Captcha system or registration doesnt work

**Current behaviour:**

doesnt work ( it reports : Captchya Broken )

**Branch(es):**

#30 

**Browser:** All

**Comment by RenegadeLegionWow** [comment]
sorry bout the #30 it doesnt apply there

**Comment by fixcore** [comment]
Incomplete issue, add screens and more info please.

**Comment by RenegadeLegionWow** [comment]
sorry it does work.. just.. there is no way to input my own keys

**Comment by RenegadeLegionWow** [comment]
i just turned it off via the mysql... so now its not a bother.. but there is no way for site owners to add their own recaptcha keys.. site needs its own admin panel

**Comment by RenegadeLegionWow** [comment]
okay i want to apologize... i found the config after some searching.. recaptcha works perfectly fine sorry to bother you
