### ISSUE TITLE
[dev] Forum-Cards and sticky topics have a broken form

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#169]
**Description:**
The forum cards are having rounded and blue edges instead of the usual ones. Same goes for sticky posts
They should not be rounded and not have a blue border

**Current behaviour:**
![forum-cards](https://user-images.githubusercontent.com/18347559/35190579-436ab9aa-fe65-11e7-9e6a-241a1390b02b.png)

![sticky news](https://user-images.githubusercontent.com/18347559/35190619-0ea2cb76-fe66-11e7-9c11-79d392cbeebe.png)

**Expected behaivior:**
Sticky topic design:
![post ordr](https://user-images.githubusercontent.com/18347559/35190816-3fa5ff36-fe6b-11e7-9b42-945d1408cd60.png)

Forum cards:
![forumcards](https://user-images.githubusercontent.com/18347559/35190821-621d4308-fe6b-11e7-9ff8-8602d51669a6.png)

**Branch(es):**
devs

**Browser:**
Firefox

**Comment by DZywolf** [comment]
Fixed in 513fa0afa322dbfc45c566254579f29987e7414b
