### ISSUE TITLE
[dev] Navigation bar is missing its background image

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#170]
**Description:**
The naviation bar currently does only have a background color since   05a4c18e2f2074e296176b8b04e162e2ad3e2e7a
This is wrong and not the design of the battle.net page.  Please revert that change since the navigation bar background image is a part of the theme.

Wrong:
![navbarwrong](https://user-images.githubusercontent.com/18347559/35190742-3667b114-fe69-11e7-95b3-8690d6b46c7e.png)

Correct:
![navbar correct](https://user-images.githubusercontent.com/18347559/35190744-39afc820-fe69-11e7-9e0e-cd5734b97e12.png)

Battle.net page as reference:
![battlenet](https://user-images.githubusercontent.com/18347559/35190760-cfdb2556-fe69-11e7-9840-c951cc1dd246.png)

**Branch(es):**
devs 

**Browser:**
Firefox

**Comment by DZywolf** [comment]
Fixed 513fa0afa322dbfc45c566254579f29987e7414b
