### ISSUE TITLE
[dev] Forum reply form sizes incorrect

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#171]
**Description:**
- according to the battle.net design the reply form should have a bigger width and also the form to type in should be more strecthed.

Current in blizzcms:
![snmall reply](https://user-images.githubusercontent.com/18347559/35190791-be7a0e98-fe6a-11e7-908b-57805ffaf7bf.png)

Battle.net Layout:
![replayretail](https://user-images.githubusercontent.com/18347559/35190792-c38d4b98-fe6a-11e7-9e04-5af734a6e085.png)

This design applies for all blizzard games.

CHANGEME Tell us what happens.
If you have images about the issue, post the images here.

**Branch(es):**
devs

**Browser:**
Firefox

**Comment by DZywolf** [comment]
Fixed in https://github.com/fixcore/BlizzCMS/pull/231
