### ISSUE TITLE
[dev] missing store group option in admin panel

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#172]
**Description:**
The admin panel for the store management is lacking a store-group manager to create shop group. Shop groups are required for creating shop items because without them you get the error:

![storeerror](https://user-images.githubusercontent.com/18347559/35190867-a0c9dffc-fe6c-11e7-9fd0-a477a99cf008.png)

**Branch(es):**
dev

**Browser:**
Firefox

**Comment by DZywolf** [comment]
Fixed in 90e91dcd927df71f8004e1658cf8f541a159b3da
