### ISSUE TITLE
<dev> Errors in server status and does not show players online

### ISSUE THREAD

**Issue by Aszune** [fixcore/BlizzCMS#174]
**Description:**

I see errors in server status and does not show the online players of each faction.

**Current behaviour:**

The Realm is detected and show online icon but I don't see the players of each faction, with errors:
![cc7eb3b4af40f4d9ca670963107b8aca](https://user-images.githubusercontent.com/4223661/35241374-966c2f06-ffb6-11e7-9bbd-ad156602489b.png)

> An uncaught Exception was encountered
> 
> Type: Error
> 
> Message: Call to undefined method CI_DB_mysqli_driver::num_rows()
> 
> Filename: D:\Programas\xampp\htdocs\blizzcms\application\models\M_general.php
> 
> Line Number: 473
> 
> Backtrace:
> 
> File: D:\Programas\xampp\htdocs\blizzcms\application\modules\home\views\home.php
> Line: 213
> Function: getCharactersOnlineAlliance
> 
> File: D:\Programas\xampp\htdocs\blizzcms\application\third_party\MX\Loader.php
> Line: 357
> Function: include
> 
> File: D:\Programas\xampp\htdocs\blizzcms\application\third_party\MX\Loader.php
> Line: 300
> Function: _ci_load
> 
> File: D:\Programas\xampp\htdocs\blizzcms\application\modules\home\controllers\Home.php
> Line: 22
> Function: view
> 
> File: D:\Programas\xampp\htdocs\blizzcms\index.php
> Line: 315
> Function: require_once

I use xampp in windows 10 localhost machine with php 7.0.18, Apache 2.4.25, Mariadb 10.1 - the realm server is in another machine, a linux debian 9 dedicated server. I setup the IP and 8085 port in cms configs

**Branch(es):**

dev branch and latest commit: https://github.com/fixcore/BlizzCMS/commit/539c46c83d2fe86c278355b4d96e41c12700ffb4

**Browser:** Firefox & Chrome

**Comment by fixcore** [comment]
Fixed in { Dev Branch } please confirm, thanks for report it

**Comment by Aszune** [comment]
Now it's fixed! 👍🏼
Looks as expected.
