### ISSUE TITLE
[dev] missing glass background image for forum navigation bar

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#177]
**Description:**
The glass effect as it is used on the battle.net page is currently not working on the forum pages. The main page works, the forums not.

On top of that the background image is not being used entirely. The cataclysm theme for example is having a rendered glass effect and this is being cut off for some reason. Here the source image. On the next screenshot you can clearly see what part is missing. This is the fx_glass image. This one is not used atm
![fx-glass](https://user-images.githubusercontent.com/18347559/35245293-595a4db6-ffc3-11e7-8363-192cd0bdae10.jpg)

**Current behaviour:**
![forumlayout](https://user-images.githubusercontent.com/18347559/35245135-d039974e-ffc2-11e7-819b-34e1f8f17eb8.png)

**Branch(es):**
 devs 

**Browser:** CHANGEME Chrome, Firefox or other

**Comment by DZywolf** [comment]
Fixed in bf0d46c88f67c0ad89d4f57c049c18c398ea8d8d

**Comment by Ovahlord** [comment]
Well, this fix is not fixing the issue properly. Now the images are smaller than before which leads to cut off-images

**Comment by DZywolf** [comment]
The images have been reversed, the change had no major effects.
previously the theme worked with the part that was cut before but breaks with the other modules such as home only giving preference to the forum. now the glass effect no longer comes only from css, so it is also necessary to add it to the images, if you have any doubt about what glass is check the images of the sliders and compare with the cataclysm theme.
Finally we take care of a "general" design, positioning, colors, sizes and things so they will be visible regardless of the theme.

**Comment by Ovahlord** [comment]
I see what you mean with your points. The fix for the images however need a different approach.  If the glass effect has been on the bottom before and now is at the top as default part of the banner, the original site images are required now to get fixed.
I was lucky enough that by background images was big enough to get the original blizzard design on that new layout for the cata theme. This one here:
![fx-glass](https://user-images.githubusercontent.com/18347559/35257413-5d5132c8-fff9-11e7-9cc8-4c60df441b9d.jpg)

Fully compatible with the new layout. This is a better solution in my opinion rather than applying a custom glass effect to avoid loss of picture parts
