### ISSUE TITLE
[dev] going one page back and forth after topic creation is causing duplicated topics

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#178]
**Description:**
When you create a topic, go one page back and then go one page forth again and you will duplicate topics after resending the informations.

**Current behaviour:**
Topics duplicate if you go one page back and forth:
![duplicate](https://user-images.githubusercontent.com/18347559/35245623-31f5c380-ffc4-11e7-996e-79cad85a94f0.png)

**Branch(es):**
devs

**Browser:**
Firefox

**Comment by fixcore** [comment]
Information not included, if you return on any website you can always see your previous form.
In BlizzCMS I see no alteration of objects to duplicate post so it is not considered a problem.

**Comment by Ovahlord** [comment]
It is like when I go back and go forth again, the browser ask me to send the information again and this causes the user to create the same topic again.
So: create topic --> go one page back --> go back to your page before you went back --> confirm the popup that you wanna send the informations again --> see the duplicate post.
Maybe the posting cooldown like in the blizzard forums might help to prevent that from happening by accident.

**Comment by fixcore** [comment]
Done, please confirm it and close issue. 
Thanks for your report

**Comment by Ovahlord** [comment]
The issue has changed now. Now when I go one page back I get the message that the document is no longer within the cache. If I refresh that site now it asks me again to re-send the information so it happens again.
Create topic --> go one page back --> refresh the page by using F5, resend information --> duplicate posts again

**Comment by fixcore** [comment]
Try again please. Thanks

**Comment by Ovahlord** [comment]
Fixed.
