### ISSUE TITLE
new news post issue

### ISSUE THREAD

**Issue by stinkyjoint** [fixcore/BlizzCMS#183]
**Description:**

when trying to make a new news post i have to upload a file before it will post

**Current behaviour:**

when trying to make a new news post i have to upload a file before it will post

**Branch(es):**

Master

**Browser:**

Chrome

**Comment by fixcore** [comment]
This isn't a problem

**Comment by stinkyjoint** [comment]
This is a problem.... I don't need to upload a file everything I make a new post...

**Comment by Ovahlord** [comment]
For forum posts or for creating news? News require a image file for visual reasons if you take a look at the default news that comes with the installation

**Comment by fixcore** [comment]
Design require a image, this isn't optional

**Comment by Ovahlord** [comment]
Can't confirm the issue here. Forum posts work as intended.

**Comment by cavaclub** [comment]
Sorry for open the issue but, keep an issue, or identical if i don't understand the meaning of this issue. it's like when editing a news we have to set always the image, while still already was uploaded before the edit.
