### ISSUE TITLE
[dev] Default forum avatar broken

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#184]
**Description:**
Since the conversion of the forum avatar from jpg to png the default forum avatar is no longer visible:
![broken](https://user-images.githubusercontent.com/18347559/35285308-510eb422-005d-11e8-8bed-a02c660f2a6e.png)

**Branch(es):**
devs

**Browser:**
Firefox

**Comment by fixcore** [comment]
https://github.com/fixcore/BlizzCMS-DATABASE/commit/0f43450f11778ca86c443c9ff034245f7d2c4671

**Comment by Ovahlord** [comment]
Didn't seem to fix the issue. The default png avatar is still not loaded even when setting this profile image in database

**Comment by DZywolf** [comment]
Fixed in https://github.com/fixcore/BlizzCMS-DATABASE/commit/7f980c81910095b8406008f69cefbae27cce7e20
