### ISSUE TITLE
[dev] Project name alignment in the nav-bar is right instead of left

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#186]
**Description:**
The project name of the navigation bar is currently aligned to the right side instead of the left side which leads to the issue that it partially overlaps with the menu dropdown:

![alignment](https://user-images.githubusercontent.com/18347559/35286734-163a4894-0061-11e8-8fa3-dd84c3b92925.png)

**Branch(es):**
both

**Comment by Orangs** [comment]
True, here is another screen from my page.
![](https://ctrlv.cz/shots/2018/01/28/PEmh.png)

**Comment by DZywolf** [comment]
Fixed in 7a58b9566eed8603b30c169500139aa537c899ca
