### ISSUE TITLE
[dev] Errors in register 7.x bnetaccounts

### ISSUE THREAD

**Issue by Aszune** [fixcore/BlizzCMS#191]
**Description:**

I see 2 issues in register module.

I have a Trinitycore 7.2.5

1. The system don't check if the email exists with other account. Results in multiple accounts and "bnetaccounts" with the same login info. In legion the game login use the email as a username account.

2. The system show a DB error when I intended register account with existent email in another account.

![09b21d70ae824369c65db4900bf7d94c](https://user-images.githubusercontent.com/4223661/35296980-ec4d8e3e-007d-11e8-9452-c74bd57f352e.png)

**Current behaviour:**

The account is created but with errors and missing information in the tables of the BD, account it's not linked with bnetaccount.

It would be appropriate for the system to detect duplicate-existing emails in use in other accounts and not create the new account, throwing out a notice to use a different email.

Sorry for my poor english :P

**Branch(es):**

dev branch: https://github.com/fixcore/BlizzCMS/commit/c555e104f608222c22c9f65cd59225be7e19a6bb

**Comment by Aszune** [comment]
The same database error, when I try to register a new account with unused information (no existing emails)...

The account was created in the emulador database but it's not linked the "account" with "battlenet_accounts"

![483ba63c3e3d4e1c7343db5bccc2460e](https://user-images.githubusercontent.com/4223661/35299132-9a32b8ca-0084-11e8-9c1a-6dff42be2ba4.png)

auth DB structure:

![b527c13ad9098438f0b64b16ad0560d2](https://user-images.githubusercontent.com/4223661/35299238-f5507026-0084-11e8-8333-2f15775ea610.png)

table "account" the cell battlenet_account it's not linked (NULL) in the latest 2 accounts (id 9 and 10)

![13a2727b4a6d5b3b691bd56a3729f7a6](https://user-images.githubusercontent.com/4223661/35299453-a8d2f57e-0085-11e8-8b80-b7ef153b6989.png)

**Comment by fixcore** [comment]
Fixed, please confirm me. If this works please close the issue

**Comment by Aszune** [comment]
Fixed, now I can create new accounts in 7.x (Legion system) :)
