### ISSUE TITLE
[dev] Store category selection dropdown menu too small

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#214]
**Description:**
The dropdown menu for selecting the category is too small which leads to the issue that the text is getting cut off: 
![dropdown](https://user-images.githubusercontent.com/18347559/35514682-4979d12a-0507-11e8-816b-c9c4272697da.png)

**Comment by DZywolf** [comment]
Fixed in 3b42e229b7c927bbd2ff1a992559cff50715104d
