### ISSUE TITLE
[dev] Many redirections are broken

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#215]
**Description:**
Many redirections to previous pages are broken now.
Extra information: this is the default theme after a fresh installation.
Update: pretty much everything that should redicrect you is broken now.

After Logging in:
![link](https://user-images.githubusercontent.com/18347559/35514810-b3f95a0c-0507-11e8-9d43-4cf55d45c9d4.png)

After updating personal information:
![panel](https://user-images.githubusercontent.com/18347559/35514953-20cf78dc-0508-11e8-9bfb-470c59929eb7.png)

After adding a comment to news:
![reply news](https://user-images.githubusercontent.com/18347559/35515030-64155832-0508-11e8-8393-accdf92c2f31.png)

**Comment by fixcore** [comment]
Please send me your config,php

**Comment by Ovahlord** [comment]
There you go:  https://paste2.org/h8XYOaDL

**Comment by fixcore** [comment]
' http://127.0.0.1/';
you have a space, replace to
 'http://127.0.0.1/';
