### ISSUE TITLE
Problems with the news edit menu

### ISSUE THREAD

**Issue by miwswingza** [fixcore/BlizzCMS#222]
Problems with the news edit menu. At the time of recording, the message will be cleared back to the original message. Who has a solution to it?

**Comment by miwswingza** [comment]
![image](https://user-images.githubusercontent.com/35965040/35573278-3679c708-0609-11e8-9355-e851aa066465.png)
original message

**Comment by miwswingza** [comment]
![image](https://user-images.githubusercontent.com/35965040/35573326-5d7995d6-0609-11e8-9266-5635c5c272ac.png)
new edit massage

**Comment by miwswingza** [comment]
![image](https://user-images.githubusercontent.com/35965040/35573365-7bec3280-0609-11e8-98d0-be76ac2d2c9d.png)
At the time of recording, the message will be cleared back to the original message.

**Comment by fixcore** [comment]
Fixed, please confirm me

**Comment by miwswingza** [comment]
Unsuccessful
