### ISSUE TITLE
Creación de páginas. No permite imágenes

### ISSUE THREAD

**Issue by tortosi** [fixcore/BlizzCMS#223]
Cuando creas una página y vas al icono de insertar imagen, no te deja modificar nada. No puedes poner ninguna url ni subir un archivo.

**Comment by fixcore** [comment]
Falta la imagen al crear una issue, por favor termina de completar tu issue para que este en revisión

**Comment by tortosi** [comment]
![captura de 2018-02-02 00-32-43](https://user-images.githubusercontent.com/160920/35707003-54dffbb8-07a8-11e8-8933-f2573ab30559.png)

Aquí, estoy creando una nueva página y quiero añadir una imagen. No me deja escribir ni cambiar ningún campo

**Comment by fixcore** [comment]
@DZywolf

**Comment by DZywolf** [comment]
Fixed in https://github.com/fixcore/BlizzCMS/pull/264
