### ISSUE TITLE
[dev] users can still do blueposts after admin rank gets removed

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#235]
**Description:**
When you create a bluepost as admin and lose your admin rank afterwards, your posts are still blueposts instead of normal ones

**Current behaviour:**
Blueposts still happen when you lose your rank after creating a bluepost entry

**Branch(es):**
both

![posts](https://user-images.githubusercontent.com/18347559/35731580-01f67524-080e-11e8-8846-b765739d1bc1.png)

**Comment by fixcore** [comment]
Works for me, remember that the rank is with your auth -> account_access, and need +1 gm level

**Comment by Ovahlord** [comment]
Good point. There is another issue though: non-admins can remove posts of other people in the topic. Should not be possible for normal members.
