### ISSUE TITLE
[dev] post-duplicate bug is back

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#237]
**Description:**
All you have to do is create a post reply and refresh the page by using F5 and resend the information:
![postbug](https://user-images.githubusercontent.com/18347559/35742576-2999bfe6-083b-11e8-89ed-6e7be7caca82.png)

**Comment by fixcore** [comment]
Please check the issue https://github.com/fixcore/BlizzCMS/issues/236
And check again this issue. Maybe the problem is fixed

**Comment by Ovahlord** [comment]
fixed
