### ISSUE TITLE
[dev] Log-out button is requesting me to re-send informations

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#241]
**Description:**
Right now when I want to log out to change the account for example my browser asks me to re-send my informations. This popup should not appear at all.
This happens mostly after creating a topic or reply and then logging out

**Comment by fixcore** [comment]
Incomplete issue, please add image

**Comment by Ovahlord** [comment]
I can tell you exactly how to reproduce this issue:
- Create a topic or post a reply
- Log out
- see how the resend window pops up.

So it is probably related to #237

**Comment by Ovahlord** [comment]
fixed
