### ISSUE TITLE
[dev] cms sometimes takes really long to load

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#242]
**Description:**
From time to time the website is having really long loading times. Sometimes for minutes. I think this is somehow connected to the import of online ressources.
Right now at the moment of this test the site is loading for 4 minutes now and still does not show up.

Edit: it appears that the cache of the site is sometimes causing issues. Emptying the browser cache was seemingly fixing the issue.

**Additional Information:**
- Browser: Firefox Quantum
- Sites tried to load: Main-Page and Forums
- Attempts to load: 5

**Comment by fixcore** [comment]
Incomplete information, we need more information, for example the specific section, specific forms

**Comment by Ovahlord** [comment]
Can't give you more information. Everything I tried to do is loading the main site.
Used Firefox Quantum if that helps somehow.

**Comment by Ovahlord** [comment]
The issue seems to be fixed. The only increase in loading times now is the server status but this only takes a few seconds.
