### ISSUE TITLE
[dev] Shop error

### ISSUE THREAD

**Issue by Orangs** [fixcore/BlizzCMS#247]
**Description:**

When i trying to buy ITEM from Shop to my character, i have this error
`A PHP Error was encountered
Severity: Warning

Message: Missing argument 2 for M_general::getNameCharacterSpecifyGuid(), called in /var/www/html/application/modules/shop/models/Shop_model.php on line 168 and defined

Filename: models/M_general.php

Line Number: 57

Backtrace:

File: /var/www/html/application/models/M_general.php
Line: 57
Function: _error_handler

File: /var/www/html/application/modules/shop/models/Shop_model.php
Line: 168
Function: getNameCharacterSpecifyGuid

File: /var/www/html/application/modules/shop/views/cart.php
Line: 25
Function: insertHistory

File: /var/www/html/application/third_party/MX/Loader.php
Line: 357
Function: include

File: /var/www/html/application/third_party/MX/Loader.php
Line: 300
Function: _ci_load

File: /var/www/html/application/modules/shop/controllers/Shop.php
Line: 58
Function: view

File: /var/www/html/index.php
Line: 324
Function: require_once

An uncaught Exception was encountered
Type: Error

Message: Call to a member function select() on string

Filename: /var/www/html/application/models/M_general.php

Line Number: 60

Backtrace:

File: /var/www/html/application/modules/shop/models/Shop_model.php
Line: 168
Function: getNameCharacterSpecifyGuid

File: /var/www/html/application/modules/shop/views/cart.php
Line: 25
Function: insertHistory

File: /var/www/html/application/third_party/MX/Loader.php
Line: 357
Function: include

File: /var/www/html/application/third_party/MX/Loader.php
Line: 300
Function: _ci_load

File: /var/www/html/application/modules/shop/controllers/Shop.php
Line: 58
Function: view

File: /var/www/html/index.php
Line: 324
Function: require_once`

**Branch(es):**

dev

**Comment by fixcore** [comment]
Fixed, please confirm me.

**Comment by Orangs** [comment]
Another error just come out. Here is error
`A PHP Error was encountered
Severity: Notice

Message: Undefined variable: multiRealm

Filename: views/cart.php

Line Number: 26

Backtrace:

File: /var/www/html/application/modules/shop/views/cart.php
Line: 26
Function: _error_handler

File: /var/www/html/application/third_party/MX/Loader.php
Line: 357
Function: include

File: /var/www/html/application/third_party/MX/Loader.php
Line: 300
Function: _ci_load

File: /var/www/html/application/modules/shop/controllers/Shop.php
Line: 58
Function: view

File: /var/www/html/index.php
Line: 324
Function: require_once

An uncaught Exception was encountered
Type: Error

Message: Call to a member function select() on null

Filename: /var/www/html/application/models/M_general.php

Line Number: 60

Backtrace:

File: /var/www/html/application/modules/shop/models/Shop_model.php
Line: 168
Function: getNameCharacterSpecifyGuid

File: /var/www/html/application/modules/shop/views/cart.php
Line: 26
Function: insertHistory

File: /var/www/html/application/third_party/MX/Loader.php
Line: 357
Function: include

File: /var/www/html/application/third_party/MX/Loader.php
Line: 300
Function: _ci_load

File: /var/www/html/application/modules/shop/controllers/Shop.php
Line: 58
Function: view

File: /var/www/html/index.php
Line: 324
Function: require_once`

**Comment by fixcore** [comment]
Confirm me again please

**Comment by Orangs** [comment]
Now issue is complete fixed. Item is arrived without problems and NO errors now. FIXED.
