### ISSUE TITLE
Remove comment in News Notworking

### ISSUE THREAD

**Issue by miwswingza** [fixcore/BlizzCMS#250]
![image](https://user-images.githubusercontent.com/35965040/35762218-c1e18966-08c5-11e8-81da-e4eae18e8115.png)
![image](https://user-images.githubusercontent.com/35965040/35762221-c97217a4-08c5-11e8-940f-306fd79bc928.png)

**Comment by Ovahlord** [comment]
Confirmed. Getting same php error:
![confirmed](https://user-images.githubusercontent.com/18347559/35854185-fd1b0608-0b2f-11e8-9484-2325dd2109f2.png)

**Comment by DZywolf** [comment]
Fixed in 227e121e6d3b24949357d9cd27286c167d5075c1
