### ISSUE TITLE
How to fix the system delete comment in the forum & news?

### ISSUE THREAD

**Issue by miwswingza** [fixcore/BlizzCMS#259]
I have coments   id =  1   2   3   4   5   6
I click button delete  coment   id=4   but system delete   id = 1
It will be deleted at the top id in database
![cats1](https://user-images.githubusercontent.com/35965040/35772372-8a2cae92-096f-11e8-96a1-bd6d36083a31.jpg)
![cats2](https://user-images.githubusercontent.com/35965040/35772379-cf4e56f6-096f-11e8-93fe-31721d4cada7.jpg)

**Comment by DZywolf** [comment]
Fixed in 227e121e6d3b24949357d9cd27286c167d5075c1
