### ISSUE TITLE
bugtracker does not show the information on the site. Only in database.

### ISSUE THREAD

**Issue by Sagrario123** [fixcore/BlizzCMS#262]
bugtracker does not show the information on the site. Only in database.

http://pvp-wow.fun/bugtracker 

http://prntscr.com/ia1ojq

**Comment by Ovahlord** [comment]
Cannot confirm. Works for me (tm)
![Uploading nope.png…]()

**Comment by miwswingza** [comment]
In folder application\modules\bugtracker\controllers rename bugtracker.php to Bugtracker.php

**Comment by fixcore** [comment]
Works for me sorry. We need more evidence

**Comment by Sagrario123** [comment]
http://pvp-wow.fun/bugtracker 07.02.2018, 19:29, "KM" <notifications@github.com>:Works for me sorry. We need more evidence

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Skreamwow.ru
