### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by irgc** [fixcore/BlizzCMS#293]
hi

i downloaded clone blizzcms and install but error!

A PHP Error was encountered
Severity: Warning

Message: mkdir() [function.mkdir]: SAFE MODE Restriction in effect. The script whose uid is 2416 is not allowed to access /tmp owned by uid 0

Filename: drivers/Session_files_driver.php

Line Number: 136

Backtrace:

File: /home1/serverg2/public_html/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home1/serverg2/public_html/application/third_party/MX/Loader.php
Line: 192
Function: library

File: /home1/serverg2/public_html/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home1/serverg2/public_html/application/third_party/MX/Loader.php
Line: 65
Function: initialize

File: /home1/serverg2/public_html/application/third_party/MX/Base.php
Line: 55
Function: __construct

File: /home1/serverg2/public_html/application/third_party/MX/Base.php
Line: 60
Function: __construct

File: /home1/serverg2/public_html/application/third_party/MX/Controller.php
Line: 4
Function: require

File: /home1/serverg2/public_html/application/third_party/MX/Modules.php
Line: 123
Function: include_once

File: /home1/serverg2/public_html/application/modules/home/controllers/Home.php
Line: 4
Function: spl_autoload_call

File: /home1/serverg2/public_html/index.php
Line: 326
Function: require_once

**Comment by cavaclub** [comment]
did you install all requirements?

**Comment by irgc** [comment]
yes!

I checked several times

but buged

**Comment by cavaclub** [comment]
do you set permissions on files and folders

**Comment by fixcore** [comment]
Permissions chmod -R

**Comment by fixcore** [comment]
The issue isn't correct, please use the chat for this thing.
https://discord.gg/WGGGVgX
