### ISSUE TITLE
soap cmangos store

### ISSUE THREAD

**Issue by cavaclub** [fixcore/BlizzCMS#298]
**Description:**

So, i have 3 cmangos realms in same server vps: classic, tbc and wotlk. I set SOAP for cmangos like on realms table with emulator "MaNGOS". But Store keep saying that send item successfully but i don't receive nothing. I just tried change to "TC" but is the same... Before i have TrinityCore 3.3.5a installed and store working perfect. I run ubuntu 17.10 server and all soap plugin installed and working. So i used a example.php that cmangos have to test soap, and work perfect. Here an example:

```php
$username = 'ADMINISTRATOR';
$password = 'ADMINISTRATOR';
$host = "localhost";
$soapport = 7878;
$command = "server info";
$client = new SoapClient(NULL,
array(
    "location" => "http:///$host:$soapport/",
    "uri" => "urn:MaNGOS",
    "style" => SOAP_RPC,
    'login' => $username,
    'password' => $password
));
try {
    $result = $client->executeCommand(new SoapParam($command, "command"));
    echo "Command succeeded! Output:<br />\n";
    echo $result;
}
catch (Exception $e)
{
    echo "Command failed! Reason:<br />\n";
    echo $e->getMessage();
}
```

**Current behaviour:**

Just saying "send item successfully" but nothing happen!

**Browser:** Firefox

**Comment by fixcore** [comment]
Please send screen 

yourdomain.com/admin/checksoap

**Comment by cavaclub** [comment]
![imagem](https://user-images.githubusercontent.com/2026665/36423002-27db4e14-1636-11e8-8036-acba367fc111.png)
after i have change ssl settings i could see checksoap page
