### ISSUE TITLE
realm status styling issue

### ISSUE THREAD

**Issue by cavaclub** [fixcore/BlizzCMS#299]
**Description:**

This issue isn't so urgent, but as i have 3 realms the status realm template seems wrong, what can i do to fix it?

http://storage1.static.itmages.com/i/18/0212/h_1518427907_1255558_87fa9caf06.png

**Current behaviour:**

3º realm looks like is turning left :D 

**Browser:** Firefox

**Comment by DZywolf** [comment]
Fixed in 8827c1f38cb6720b026a253b07bf45cddf914252
