### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by irgc** [fixcore/BlizzCMS#302]
all time error install!

mysql and apach for xampp last version

 Requirements

 HOST REQUIREMENTS

Minimum PHP 5.6

 APACHE MODULES REQUIRED

mod_rewrite, mod_headers, mod_expires, mod_deflate

 PHP EXTENSIONS REQUIRED

php_curl, php_openssl, php_soap, php_gd, php_mbstring, php_json

and install done!

Warning: file_get_contents(fixcore.php.dist): failed to open stream: No such file or directory in /opt/lampp/htdocs/c/install/index.php on line 19

Warning: file_get_contents(config.php.dist): failed to open stream: No such file or directory in /opt/lampp/htdocs/c/install/index.php on line 40

Warning: mysqli::__construct(): (HY000/2002): Connection refused in /opt/lampp/htdocs/c/install/settings.php on line 5
Connect Error (2002) Connection refused

!!!!!!!!!!!

**Comment by Ovahlord** [comment]
Did a clean install right now. Didn't have such issues. Can't confirm.

**Comment by irgc** [comment]
What do you install  mysql with! xampp?

**Comment by Ovahlord** [comment]
Xampp and I installed MySQL standalone before. So I don't use the xamp internal
