### ISSUE TITLE
[dev] News page is missing a white line between the top news and news section

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#306]
**Description:**
The news page is currently missing a white line that should be between the top news and news section:

Currently on blizzcms
![cms](https://user-images.githubusercontent.com/18347559/36138642-7eb47ad6-109a-11e8-9076-661a3c762a43.png)

Now the blizzard one:
![blizzard](https://user-images.githubusercontent.com/18347559/36138646-872a77c4-109a-11e8-8921-4f21066eaf0d.png)

This issue applies for all themes.

**Comment by DZywolf** [comment]
Reference to theme obsolete

**Comment by Ovahlord** [comment]
That's not true. This is the default theme and it applies to all themes cuz it is not really a theme related issue, it is a cms issue.

**Comment by fixcore** [comment]
We don't try clone the theme Blizzard. We are creating our style.
