### ISSUE TITLE
[dev] new installer asks me to delete my install folder before completing installation

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#307]
**Description:**
When doing a clean installation, the installer asks me to delete my install folder after I added the first database informations. Should not happen.

**Current behavior:**
- After completing the install step where you have to add your auth and cms database informations, the installer asks me to delete the folder.

**Expected behaivior:**
- The installer should ask for deleting the folder after all steps have been completed.

**Browser:** 
Firefox

**Comment by DZywolf** [comment]
Fixed 30f8eefaef6c1311431897906d878dfa59b21f6f
