### ISSUE TITLE
[dev] the reply-form when commenting news has a wrong size

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#309]
**Description:**
When adding a comment to news the text form has a wrong size. The gap between the user and the reply form needs to be smaller.

![text window](https://user-images.githubusercontent.com/18347559/36139226-04708ae6-109d-11e8-8ed0-37f4d265f304.png)

**Browser:**
Firefox

**Comment by DZywolf** [comment]
Reference to theme obsolete
