### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by jyrixx** [fixcore/BlizzCMS#310]
Not Found

The requested URL /news was not found on this server.

i have normally installed blizzcms and my website is broken look: http://institution-wow.de/

**Comment by Ovahlord** [comment]
Don't open a ticket for that. Use the discord support channel instead.

**Comment by irgc** [comment]
dont found? .htdocss on blizzcms ?

**Comment by fixcore** [comment]
Woking, only enable the extension in your apache
