### ISSUE TITLE
[dev] Installer skips 2nd step entirely. Can't assign admin account or first realm anymore

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#314]
**Description:**
The setup now instantly skips the 2nd installation step so you cannot add the first realm for the realm status anymore or assign a admin rank account

**Current behaviour:**
After completing Step 1 (auth and cms database setup) the installer skips the 2nd part of the setup.

**Browser:** 
 Firefox

**Comment by DZywolf** [comment]
Fixed a5c083aa5bb2809c6c3da068e5b386ced84757bd
