### ISSUE TITLE
error statistics maybe when 3 realms

### ISSUE THREAD

**Issue by cavaclub** [fixcore/BlizzCMS#315]
**Description:**

As i have 3 realms cmangos (classic, tbc and wotlk), this happens:
http://storage8.static.itmages.com/i/18/0215/h_1518697571_9639021_7841edc204.png
and also this on arena:
http://storage1.static.itmages.com/i/18/0215/h_1518697864_5944629_843b53b170.png

**Current behaviour:**

seems gives that errors

**Browser:** Firefox

**Comment by fixcore** [comment]
Update the code and resend screenshot errors please

**Comment by cavaclub** [comment]
http://storage5.static.itmages.com/i/18/0218/h_1518945547_7035807_ca372ecba5.png

http://storage6.static.itmages.com/i/18/0218/h_1518945571_3323262_174818a0e3.png

**Comment by cavaclub** [comment]
i have checked and the error seems to be because cmangos realms dont have the requested columns... ('name, race, totalKills, todayKills, yesterdayKills') on characters only have name and race. As you can see here: https://github.com/cmangos/issues/wiki/characters#structure

Then the Arena have 3 tables blizzcms need to check you can be found more info here:
https://github.com/cmangos/issues/wiki/charactersdb_struct#this-is-the-list-of-tables-in-the-characters-database and is same/almost the same for all versions: classic, tbc or wotlk!

As i could see on code from PVP and ARENA from blizzcms only have support for TC!

**Comment by fixcore** [comment]
Thank you, soon we well to update the code for support mangos and more emulators, please wait maybe 1 day

**Comment by cavaclub** [comment]
ok thank you!

**Comment by cavaclub** [comment]
i cannot support anymore this issue, do not have cmangos, to test it.
