### ISSUE TITLE
How can i access the admin panel?

### ISSUE THREAD

**Issue by Cubansephiroth** [fixcore/BlizzCMS#32]
How can i give admin access to an account?
I am testing the CMS with a WoD source. I can create an account and login without problems but i dont know where to give my account an admin access.
Any idea? btw amazing job with this cms.

**Comment by fixcore** [comment]
http://projectscms.ml/showthread.php?tid=6

**Comment by Cubansephiroth** [comment]
Thankss!!! Solved. Closing in 3..2..1.....
