### ISSUE TITLE
display the error .css

### ISSUE THREAD

**Issue by miwswingza** [fixcore/BlizzCMS#331]
After commenting on News and Forum Will this be enough to fix it?
Including deleting comments on News and Forum

After purchasing the item in the store, it will display the error. For example, with the problem with. News and Forums.
![cats](https://user-images.githubusercontent.com/35965040/36348576-032410d4-14a5-11e8-9b8b-ccbce149277f.jpg)
![cats](https://user-images.githubusercontent.com/35965040/36348578-081fe1a8-14a5-11e8-82c0-f7cdc51df61e.jpg)

**Comment by DZywolf** [comment]
Fixed issue in f7d9908e5ce217b8e026cfeb972d41b77406e527
