### ISSUE TITLE
[Devs] Store not Delivering

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#333]
**Description:**
https://i.gyazo.com/a0ce6564e9f69f30e6ec9e0826601b85.png
The Store is not sending the Items In-game 

**Current behaviour:**

Item purchased successfully.
Shows in Store History Database
Dose not send mail to Selected char.
Uses up Points

**Browser:** Firefox

**Comment by fixcore** [comment]
youdomain.com/admin/checksoap

please send screen

**Comment by Nupper** [comment]
![image](https://user-images.githubusercontent.com/6026902/36358084-10307d5c-1500-11e8-96a3-fb58de269b9b.png)

**Comment by fixcore** [comment]
https://github.com/fixcore/BlizzCMS/commit/987a9b523f95b4d556fe49faee19128a5dccf97f 

Fixed, check and confirm me
