### ISSUE TITLE
Some ideas...

### ISSUE THREAD

**Issue by Cubansephiroth** [fixcore/BlizzCMS#34]
I was testing the cms and is very good even in development stage. Some ideas you could (or not) possible add in future updates.

- [x] Can global enable or disable user settings like (password and email change) 
- [x] Can manage user registration options (Instant activation, mail activation required)
- [x] Force users to use security questions in order to change password and email address
- [x] Can manage custom top menu items for custom pages or external links like (bugtracker-Rules-etc)
- [x] A maintenance mode will be great (only admins can log in)

That's all for now. 
Keep the good work!!!

**Comment by Tyrelis** [comment]
I like those ideas.

**Comment by fixcore** [comment]
I like, thanks for this!..
