### ISSUE TITLE
[Devs] Store settings

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#343]
**Description:**

Store settings

**Current behaviour:**

Store keeps switching back to images when Icons are selected.

**Browser:** Firefox.

**Comment by cavaclub** [comment]
print please

**Comment by fixcore** [comment]
no screen. Incomplete issue.

**Comment by Nupper** [comment]
![image](https://user-images.githubusercontent.com/6026902/36630655-dc380f90-1961-11e8-8081-2ffa0cd42ff9.png)
I set it to icons but kept being switched back.
