### ISSUE TITLE
[dev] vote panel showing empty items

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#350]
**Description:**
The vote panel shows empty vote items. Should not be visible when no vote pages are defined.

![votepanel](https://user-images.githubusercontent.com/18347559/36543726-e576df56-17e4-11e8-9953-5cacc6f4c4c4.png)

**Comment by cavaclub** [comment]
i think still in development, and not finished

**Comment by fixcore** [comment]
Vote system isn't finished. Please read the modules in progress when we create a commit.
