### ISSUE TITLE
[dev] staff replies are not blue

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#353]
Old bug is back. Replies as staff member does not turn the replies blue. Initial post works, the replies not:

![replies](https://user-images.githubusercontent.com/18347559/36561878-638aaa0a-1815-11e8-9e1d-bf3d24dd2ac4.png)

**Comment by DZywolf** [comment]
Fixed in 065acd66dd81f5a4288b2087d1ce6e2329c9ca23
