### ISSUE TITLE
[dev] small news sliders are partially cutting of texts

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#355]
**Description:**
The small sliders for news are cutting off the title text partially because they are too high or the font is too big:
![cutoff](https://user-images.githubusercontent.com/18347559/36562558-a55b9f32-1817-11e8-95cf-86c5ef76a002.png)

**Comment by fixcore** [comment]
This is a custom theme, use our framework uikit. Or you can create custom css.
