### ISSUE TITLE
News Commenting System

### ISSUE THREAD

**Issue by Mtechnik** [fixcore/BlizzCMS#356]
**Description:**
2 things I noticed, ![Screenshot 1](https://goo.gl/4QNAQJ) & ![Screenshot 2](https://drive.google.com/file/d/1DdThhGbMBIAqoul7OtHHTYtDkxuYqUvi/edit?disco=AAAABoMGplg)

**Current behaviour:**

Once the comment has been submitted, it seems to not save it in the database OR it just dont show up at all.

**Browser:** This is from both Chrome, Firefox or Explorer

**Comment by Mtechnik** [comment]
Please be more collaborative on your "Invalid-CantReproduce"

**Comment by Ovahlord** [comment]
Drag and drop the images directly into github. Your links to the screenshots are broken.

**Comment by fixcore** [comment]
Incomplete issue.
