### ISSUE TITLE
Characters connected

### ISSUE THREAD

**Issue by RebornSpartan** [fixcore/BlizzCMS#368]
**Description:**

The module to see how many alliance and horde are connected remains Zero, even if there are connected players.

On the admin panel it works, we see the number of players connected.

**Browser:** Firefox

**Comment by fixcore** [comment]
Incorrect report, we need image. Please create correctly the issues.

**Comment by RebornSpartan** [comment]
Sorry..
On the administration panel, we can see the players connect (at least the number) 

screen: 
![user_connected_admin](https://user-images.githubusercontent.com/35696045/36716680-7c55a966-1b9b-11e8-8559-8681744bd20f.PNG)

And against the site (front) and no player is seen connected. 

Screen:
![user_connected](https://user-images.githubusercontent.com/35696045/36716718-9d68ca84-1b9b-11e8-9107-334be98bc585.PNG)


He should put me 1 Alliance 0 Horde.

**Note that this is a player account and NOT a admin acc.

**Comment by fixcore** [comment]
Fixed, please confirm me

**Comment by RebornSpartan** [comment]
Hi

Now, he say " Reaml is Offline "

![offline_realm](https://user-images.githubusercontent.com/35696045/36804117-e23cb3d6-1cb9-11e8-935d-14e80141fed9.PNG)

In admin panel, the players are displayed correctly

**Comment by fixcore** [comment]
http://mundowarcraft.net/

Working correctly, check your configuration fx_realms
