### ISSUE TITLE
[Devs] Store Catagorys bugged + Store resets to Images

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#371]
**Description:**

![image](https://user-images.githubusercontent.com/6026902/36727543-8fadf4ae-1bb5-11e8-8752-c4cc4ff90172.png)

**Current behaviour:**

When set to icons after a while it reverts back to images.
All items in store are in all catagories.

**Browser:** Firefox

**Comment by fixcore** [comment]
I don't understand, when you use "select a category" this redirect to specific category and show the store with the specific items at the category

**Comment by Nupper** [comment]
you can clearly see the catagory is assigned to "Pets" but its displaying mounts.

and i had the thing set to icons instead of images and it reverted bacl.
