### ISSUE TITLE
[Devs] Donate setting errors

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#372]
**Description:**
![image](https://user-images.githubusercontent.com/6026902/36727650-fd03bfd4-1bb5-11e8-81a9-07676c0e7635.png)
![image](https://user-images.githubusercontent.com/6026902/36727656-05029f34-1bb6-11e8-9044-203d662fc5cb.png)
![image](https://user-images.githubusercontent.com/6026902/36727668-0c65451a-1bb6-11e8-830d-5c6194717256.png)
![image](https://user-images.githubusercontent.com/6026902/36727672-11517f08-1bb6-11e8-81a8-b7e0fdd1d99a.png)

**Current behaviour:**

Errors in donation settings looping into other settings.

**Browser:** Firefox

**Comment by RebornSpartan** [comment]
Hello,

It works very well.
Check the configurations and if you have activated the prerequisites

![donate_setting](https://user-images.githubusercontent.com/35696045/36781849-70b424fc-1c77-11e8-9054-d516d7dbdcee.PNG)

**Comment by fixcore** [comment]
Donate system isn't finished.

**Comment by Nupper** [comment]
Errors appear when Donation Module is Disabled.
