### ISSUE TITLE
Vote system

### ISSUE THREAD

**Issue by RebornSpartan** [fixcore/BlizzCMS#376]
**Description:**
hi,

It may be voluntary, but you forgot to put the tables in the database for the voting system. This creates a connection error to the table ....

Error page: 

> Error Number: 1146
Table 'database_name.fx_votes' doesn't exist
SELECT * FROM `fx_votes`
Filename: modules/vote/models/Vote_model.php
Line Number: 14

**Browser:** CHANGEME Firefox or other

**Comment by fixcore** [comment]
Fixed, thank you so much
