### ISSUE TITLE
Bug pag Store

### ISSUE THREAD

**Issue by MaikOshyng** [fixcore/BlizzCMS#379]
**Description:**

Tengo un bug en la pagina Tienda

Buen día, para reportar que en la tienda cada vez que le doy a comprar un item para seleccionar el personaje al que se le va a dar **no me sale la lista de personajes**.

Que es lo que puede causar este error.

![captura de pantalla 83](https://user-images.githubusercontent.com/23531197/36855726-4166125c-1d42-11e8-9a12-14684bbe6065.png)

**Comment by RebornSpartan** [comment]
Hello,
1. You do not have a character on your account
2. The database "characters" is not properly linked to the site (be careful that your password does not contain any special letters like & ~ "#) | etc ...)

At home, it works very well:
![shop_true](https://user-images.githubusercontent.com/35696045/36859446-a41b5e5c-1d7e-11e8-8c58-b1dcd47374d7.PNG)

Is not de problem in the code.

**Comment by MaikOshyng** [comment]
Yes Error Database

**Comment by MaikOshyng** [comment]
pero ya cada vez que le doy a Comprar me sale este error 


An uncaught Exception was encountered
Type: Error

Message: Class 'SoapClient' not found

Filename: C:\xampp\htdocs\application\models\M_soap.php

Line Number: 8

Backtrace:

File: C:\xampp\htdocs\application\models\M_soap.php
Line: 28
Function: connect

File: C:\xampp\htdocs\application\modules\shop\models\Shop_model.php
Line: 174
Function: commandSoap

File: C:\xampp\htdocs\application\modules\shop\views\cart.php
Line: 26
Function: insertHistory

File: C:\xampp\htdocs\application\core\MY_Loader.php
Line: 103
Function: include

File: C:\xampp\htdocs\application\third_party\MX\Loader.php
Line: 300
Function: _ci_load

File: C:\xampp\htdocs\application\modules\shop\controllers\Shop.php
Line: 69
Function: view

File: C:\xampp\htdocs\index.php
Line: 326
Function: require_once

![captura de pantalla 86](https://user-images.githubusercontent.com/23531197/36859567-c59c6332-1d4c-11e8-8adf-ac06aea30ec4.png)

![captura de pantalla 87](https://user-images.githubusercontent.com/23531197/36859574-cb1ec5b6-1d4c-11e8-9802-181ed365828a.png)

**Comment by RebornSpartan** [comment]
Install SOAP module and check your setting in the wordserver.conf ( SOAP Network )

**Comment by MaikOshyng** [comment]
Yes
