### ISSUE TITLE
Changelogs error

### ISSUE THREAD

**Issue by bahajan95** [fixcore/BlizzCMS#47]
I wanted to add some changes on the server but at the changelogs here such error
![default](https://user-images.githubusercontent.com/13211961/34067709-10d46a68-e24f-11e7-998e-d9bbda081cc8.png)
and another question how to add another realm?
sorry for bad English

**Comment by fixcore** [comment]
https://github.com/fixcore/BlizzCMS-DATABASE/tree/master/updates

**Comment by bahajan95** [comment]
oh sorry I wasn't paying attention, but how to add another realm?

**Comment by fixcore** [comment]
For the moment only you can add 1 realm

**Comment by fixcore** [comment]
https://github.com/fixcore/BlizzCMS-DATABASE

**Comment by bahajan95** [comment]
thank

**Comment by bahajan95** [comment]
you can add partners I will use this website and to help develop
the link to my site in a test http://test.iwow.uz

**Comment by fixcore** [comment]
Thanks for use my project, you can join https://discord.gg/WGGGVgX if you want

If you want partner rank:
http://projectscms.ml/showthread.php?tid=12
