### ISSUE TITLE
Store Idea

### ISSUE THREAD

**Issue by talamortis** [fixcore/BlizzCMS#52]
Hi, Just like to say great work!

Just wondering if you would make a gifting part to the store which a user could buy a item for another user this could be a option to add to the store as I think it would be very handy to have also there should be an enable or disable feature for this if it would get implemented.

**Comment by fixcore** [comment]
Hello, thanks! 

[Spoiler Alert]

http://prntscr.com/hoipa3

**Comment by talamortis** [comment]
nice 👍
