### ISSUE TITLE
Account settings not working

### ISSUE THREAD

**Issue by bahajan95** [fixcore/BlizzCMS#57]
after last update account settings not working
and i enabled in database fx_modules all modules but not working Ladder Arena, changelogs, bugtracker, support look in my site url - test.iwow.uz

**Comment by fixcore** [comment]
you are using the "dev" branch, this has many errors, for correct use use "master"

**Comment by bahajan95** [comment]
i cloned master in my web

**Comment by fixcore** [comment]
http://test.iwow.uz/

you have the module "maintenance"
this module is not releasing in "master"

**Comment by bahajan95** [comment]
https://github.com/fixcore/BlizzCMS/commits/master
it master brach yes? 
you need check it 
I CLONED MASTER and i enabled in database fx_modules all modules but not working Ladder Arena, changelogs,  and icons class in top kills 
![image](https://user-images.githubusercontent.com/13211961/34077220-29866e04-e320-11e7-88e5-e82a1ff5436b.png)
до обновления хотя бы иконки отображались у классов

**Comment by fixcore** [comment]
http://test.iwow.uz/login

You continue with branch "dev" if you clone with command then use 

git clone -b master https://github.com/fixcore/BlizzCMS.git

**Comment by bahajan95** [comment]
well now I'll try again

**Comment by fixcore** [comment]
Foxed

**Comment by fixcore** [comment]
Foxed

**Comment by fixcore** [comment]
Fixed

**Comment by bahajan95** [comment]
Thanks
