### ISSUE TITLE
Issue list December 23rd 2017

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#69]
The current revision of this repository  while writing this list is: 463a9adf0617fd2367cdaf168fa15c7ce7740fa5

**Installer**
- German language is missing when selecting the cms language. Support for German language has been added with the latest update

**Main Site**
- The title of the server in the top left corner has a wrong font color and overlaps with the remaining navigation bar elements:
![overlapp](https://user-images.githubusercontent.com/18347559/34319091-09eee4aa-e7d9-11e7-98fa-d10b9dec9d2b.png)
- The navigation bar link for the bug tracker still shows up even when the bugtracker is disabled in `fx_modules`. The bugtracker link should disappear from the navigation bar when the module is disabled or has no entry in the fx_modules table.

**Server Status Module**
- The Server status shows the realm as online even when the realm is completely offline.
- When the server is offline, the online status shows a single alliance player as online player which is impossible when the server isn't even online:
![status](https://user-images.githubusercontent.com/18347559/34319159-1f58c6f6-e7db-11e7-9c64-5d65d662b9b8.png)

**Topic Editor**
- The current editor for new topics seems to be broken. Formation tools are completely missing and the text field seems to be broken as well:
![brokentool](https://user-images.githubusercontent.com/18347559/34319139-992e2616-e7da-11e7-94b2-234cde9f6867.png)

**Login**
- The current text fields for the login are not displaying any letters or signs:
![brokenlogin visuals](https://user-images.githubusercontent.com/18347559/34319153-f0ded9aa-e7da-11e7-8a4e-9695986c1250.png)

**Pvp Statistics**
- the counter for kills is showing an wrong number. A character with 0 kills has like 1896554 displayed

**Comment by Nupper** [comment]
Main Site - has been a known issue from the start
Forum Types - are controlled by Accounts_Access tables.

 the others i will test.

**Comment by Nupper** [comment]
- Shop 
No catagorys in BlizzCMS them. Alignment issues in other themes.
Alignment
![untitled](https://user-images.githubusercontent.com/6026902/34319392-27fe09bc-e7d9-11e7-9abd-0099737b15ac.png)
No grouping tab.
![untitled2](https://user-images.githubusercontent.com/6026902/34319393-306f162c-e7d9-11e7-899a-56f446529c7d.png)

I can confirm the login issue is there.
I can confirm issues with text editor.
White box as the base of Default theme.
![untitled3](https://user-images.githubusercontent.com/6026902/34319403-94e45cb6-e7d9-11e7-8b11-fc2c8bab787b.png)
No avatar options.
I can confirm realm remains online when its offline
No forum back navigation on Default theme.

i will find more over time...i do apologize.

**Comment by fixcore** [comment]
_The title of the server in the top left corner has a wrong font color and overlaps with the remaining navigation bar elements:_ 
Now the color is #fff; #82de16f
The overlay is because its name is extensive, please modify it in "fixcore.php"

**Comment by Ovahlord** [comment]
so the installer needs an update to avoid extensive names

**Comment by fixcore** [comment]
_The navigation bar link for the bug tracker still shows up even when the bugtracker is disabled in fx_modules. The bugtracker link should disappear from the navigation bar when the module is disabled or has no entry in the fx_modules table._

Fixed! #a623cf8

**Comment by fixcore** [comment]
No avatar options.
?

**Comment by fixcore** [comment]
When the server is offline, the online status shows a single alliance player as online player which is impossible when the server isn't even online:

Fixed
