### ISSUE TITLE
Huge error

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#76]
Huge error on the main page.
![image](https://user-images.githubusercontent.com/6026902/34326226-e2beed36-e89f-11e7-838c-79d191caeec4.png)

**Comment by fixcore** [comment]
Verify if you have this in application/models/m_modules.php

> public function getStatusLadBugtracker()
	{
		return $this->db->query("SELECT status FROM fx_modules WHERE id = '16'")->row()->status;
	}

**Comment by Nupper** [comment]
16 dose not exist in updated database.

**Comment by fixcore** [comment]
http://prntscr.com/hrp7iy

I can see.
Please update your database.

https://github.com/fixcore/BlizzCMS-DATABASE/tree/master/structure
