### ISSUE TITLE
Default theme has not shop catagorys

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#77]
all items are in page and not grouped.
![image](https://user-images.githubusercontent.com/6026902/34326245-2b4136f4-e8a0-11e7-9c5f-8dacdc2372f1.png)

**Comment by fixcore** [comment]
The theme is bugged. Change your theme

**Comment by Ovahlord** [comment]
I would still consider it a issue. If it is bugged and a part of the base cms it is indeed a issue

**Comment by fixcore** [comment]
It is, but the priority is not high.

**Comment by Nupper** [comment]
![image](https://user-images.githubusercontent.com/6026902/34326296-e6fb044c-e8a0-11e7-8deb-3c93bb5f26c2.png)
Allignment issue for item currency's box.

**Comment by Ovahlord** [comment]
But please keep it open then so it wont get forgotten.

**Comment by fixcore** [comment]
@Nupper it's already fixed.

https://github.com/fixcore/BlizzCMS/issues/69

**Comment by Nupper** [comment]
i did a fresh update just now its not fixed.

**Comment by fixcore** [comment]
Repairs are not found in master branch.
Atm works only in branch dev
