### ISSUE TITLE
Cannot see login information when logging in

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#78]
Username and the password dots are not displaying.
![image](https://user-images.githubusercontent.com/6026902/34326307-28c07722-e8a1-11e7-83c8-e5900a2f7613.png)

**Comment by Ovahlord** [comment]
wasn't this issue adressed with my report?

**Comment by Cubansephiroth** [comment]
Confirmed in f5dc84c3c58080828a23a5327f7248cc66e0e737

**Comment by DZywolf** [comment]
Fixed in 635ebae4c04ecb79adb461f2e7c3a40cf28d040f
