### ISSUE TITLE
Cannot read bugreports

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#86]
After Posted
![image](https://user-images.githubusercontent.com/6026902/34356888-f18f52c4-ea39-11e7-8954-dec5be9fb693.png)

Cannot read the posted bugreport.
![image](https://user-images.githubusercontent.com/6026902/34356882-deec0fcc-ea39-11e7-819e-b1e52c381ec1.png)

**Comment by fixcore** [comment]
Fixed! already works in Dev Branch

**Comment by Nupper** [comment]
Sorry didn't notice
