### ISSUE TITLE
[Dev] Catagories do not function on shop

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#87]
I have selected toys and everything shows
![image](https://user-images.githubusercontent.com/6026902/34357084-faa90696-ea3b-11e7-9c7a-8d8c47947be7.png)

**Comment by Ovahlord** [comment]
on top of that some themes does not display categories below the navigation bar.

**Comment by Nupper** [comment]
thats for default theme only.

**Comment by DZywolf** [comment]
Fixed in 5a7e61163ff4490bee4f720d2b42adaad5760394

**Comment by Nupper** [comment]
Confirmed this works
