### ISSUE TITLE
[Dev] Can only delete managed items in Admin Panel. - Low Priority.

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#89]
You can only delete the items and not edit them.
Shop
![image](https://user-images.githubusercontent.com/6026902/34357222-18830d8c-ea3d-11e7-991a-8a67bc6bb140.png)
Changelog
![image](https://user-images.githubusercontent.com/6026902/34357227-24616b58-ea3d-11e7-8875-8769be0049dc.png)
Forums - Catagory
![image](https://user-images.githubusercontent.com/6026902/34357231-2f756846-ea3d-11e7-84aa-f3c052ec2670.png)
Forums - Topics
![image](https://user-images.githubusercontent.com/6026902/34357238-42bd6854-ea3d-11e7-967e-c32b88e9317f.png)

**Comment by fixcore** [comment]
This ins't a issue.

**Comment by Nupper** [comment]
i did mention that.
