### ISSUE TITLE
[Dev] Avatars not displayed

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#90]
Cannot select or see any avatars.
![image](https://user-images.githubusercontent.com/6026902/34357367-71a6685e-ea3e-11e7-876f-36fa73484a7c.png)

**Comment by fixcore** [comment]
Fixed!
https://github.com/fixcore/BlizzCMS-DATABASE/commit/23782cc986706eb8feae94fe05285dbe6a2ca98c

**Comment by Nupper** [comment]
After applying database
![image](https://user-images.githubusercontent.com/6026902/34357469-577a1eb6-ea3f-11e7-9015-20ff78c82861.png)

**Comment by Ovahlord** [comment]
I am currently only encountering the issue that the miniature avatar at the top corner is not showing up properly like on nupper's screenshot

**Comment by fixcore** [comment]
https://github.com/fixcore/BlizzCMS/commit/0bdd2cf4c634222af028ef6c29c98b3be3f4389a

**Comment by fixcore** [comment]
Confirm me to close issue please.

Thanks for posting the problem
