### ISSUE TITLE
[Dev] Curse of the White Spaces.

### ISSUE THREAD

**Issue by Nupper** [fixcore/BlizzCMS#91]
The Whitespaces Remain.
![image](https://user-images.githubusercontent.com/6026902/34357660-daf4a9ae-ea40-11e7-8ff7-a473b8c207ed.png)
![image](https://user-images.githubusercontent.com/6026902/34357664-e1725ce0-ea40-11e7-9553-f65c05737849.png)
![image](https://user-images.githubusercontent.com/6026902/34357677-fcf974a8-ea40-11e7-8ed5-146bd0814970.png)

**Comment by Nupper** [comment]
![image](https://user-images.githubusercontent.com/6026902/34367008-8bf7b772-ea9c-11e7-8204-daf1e3f59d36.png)
![image](https://user-images.githubusercontent.com/6026902/34367012-93f8964e-ea9c-11e7-8fe2-c6efbbb253c8.png)
![image](https://user-images.githubusercontent.com/6026902/34367015-9b3816d2-ea9c-11e7-854e-72040986c682.png)

**Comment by DZywolf** [comment]
Fixed in 43d441be5f88b724ed659b04ce32db50562c558a
