### ISSUE TITLE
[dev] Avatars in avatar selection are cutting off sometimes

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#94]
The current selected avatar is overlapping with the other avatar options
![avatarissue](https://user-images.githubusercontent.com/18347559/34366937-39c3ee60-eaa3-11e7-9d62-7267fd75275c.png)

**Comment by DZywolf** [comment]
Fixed in 22a739c4fb8f4705c2a67a6a45a4f396f1adb52c
