### ISSUE TITLE
Empty News page is causing php errors

### ISSUE THREAD

**Issue by Ovahlord** [fixcore/BlizzCMS#96]
When having a completely empty news database the site gives you php errors:

![unbenannt](https://user-images.githubusercontent.com/18347559/34411440-da3fde56-ebd6-11e7-86ee-ad699282fd1c.jpeg)

**Comment by fixcore** [comment]
Confirm me if it has already been solved.

**Comment by Ovahlord** [comment]
cannot confirm. still happens to me.
